### ISSUE TITLE
OIDC Authentication Failure: Received Forbidden Response from JWT API

### ISSUE THREAD

**Issue by 13013SwagR** [github/actions-oidc-debugger#13]
### Description:
I've been using the actions-oidc-debugger successfully in the past, but recently, without any changes to my configuration, it has stopped working and now returns a `Forbidden` error when attempting to authenticate using OIDC.

### Error Message:
```
received non-200 from jwt api: Forbidden
```

### Configuration:
Here's the relevant part of the GitHub Actions workflow configuration, which is closely based on the official documentation:

```yaml
jobs:
  debug-oidc:
    permissions:
      contents: read
      id-token: write
    runs-on: [self-hosted, micro]
    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          ref: main
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: 'https://github.com/github'
```

### Expected Behavior:
The OIDC authentication should complete successfully as it had in the past, allowing the workflow to proceed without authentication errors.

### Actual Behavior:
The workflow fails during the OIDC authentication step with a Forbidden error, indicating a lack of permission or other authorization issues.

### Additional Context:
No changes were made to the GitHub Actions permissions or runner configuration prior to the onset of this issue.
This issue started occurring recently, suggesting a possible external change in the handling of OIDC requests or a change in API behavior.

Can you validate it still works the same on your side ?

**Comment by joaopenteado** [comment]
I'm experiencing the exact same problem right now.

**Comment by joshjohanning** [comment]
@13013SwagR @joaopenteado The documentation doesn't really call this out, but you have to update the `audience` parameter from `https://github.com/github` to your organization name. Example using variables:

```yml
  print-oidc-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout actions-oidc-debugger
      uses: actions/checkout@v4
      with:
        repository: github/actions-oidc-debugger
        ref: main
        path: ./.github/actions/actions-oidc-debugger
    - name: Debug OIDC Claims
      uses: ./.github/actions/actions-oidc-debugger
      with:
        audience: '${{ github.server_url }}/${{ github.repository_owner }}'
```

This prints: 

```json
{
  "jti": "ff953027-169c-440e-9b2d-4c1013b9abcf",
  "sub": "job_workflow_ref:joshjohanning-org/oidc-claims-demo/.github/workflows/azure-oidc-demo.yml@refs/heads/main",
  "aud": "https://github.com/joshjohanning-org",
  "ref": "refs/heads/main",
  "sha": "e9c9f65767da34304ad442cc27627bba942f21c4",
  "repository": "joshjohanning-org/oidc-claims-demo",
  "repository_owner": "joshjohanning-org",
  "repository_owner_id": "95450610",
  "run_id": "9113947298",
  "run_number": "30",
  "run_attempt": "1",
  "repository_visibility": "public",
  "repository_id": "702465634",
  "actor_id": "19912012",
  "actor": "joshjohanning",
  "workflow": "Azure OIDC Demo",
  "head_ref": "",
  "base_ref": "",
  "event_name": "push",
  "ref_protected": "false",
  "ref_type": "branch",
  "workflow_ref": "joshjohanning-org/oidc-claims-demo/.github/workflows/azure-oidc-demo.yml@refs/heads/main",
  "workflow_sha": "e9c9f65767da34304ad442cc27627bba942f21c4",
  "job_workflow_ref": "joshjohanning-org/oidc-claims-demo/.github/workflows/azure-oidc-demo.yml@refs/heads/main",
  "job_workflow_sha": "e9c9f65767da34304ad442cc27627bba942f21c4",
  "runner_environment": "github-hosted",
  "enterprise_id": "2",
  "enterprise": "avocado-corp",
  "iss": "https://token.actions.githubusercontent.com",
  "nbf": 1715868442,
  "exp": 1715869342,
  "iat": 1715869042
}
```
