### ISSUE TITLE
Obtaining token to run in another repo

### ISSUE THREAD

**Issue by wassp-ds** [github/actions-oidc-debugger#17]
How do I `checkout` the repo? In other words, how to obtain the token? I am confused about the `README` instructions  :slightly_smiling_face:

**Comment by mcurole** [comment]
I was able to use the action directly. This is how I called it. 

Change the on tag as needed.

```yaml
name: OIDC Debug
on: workflow_dispatch

jobs:
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: '${{ github.server_url }}/${{ github.repository_owner }}'
```
